name: Docker Publish Prod
# Publish Production images to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build-python36:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "python-3.6"
        context: python/.
        dockerfile: python/3.6/Dockerfile

  build-python37:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "python-3.7"
        context: python/.
        dockerfile: python/3.7/Dockerfile

  build-python38:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "python-3.8"
        context: python/.
        dockerfile: python/3.8/Dockerfile

  build-python39:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "latest,python-latest,python-3.9"
        context: python/.
        dockerfile: python/3.9/Dockerfile

  build-node12x:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "node-12.22"
        context: node/.
        dockerfile: node/12.22/Dockerfile

  build-node14x:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "node-latest,node-14.18"
        context: node/.
        dockerfile: node/14.18/Dockerfile
