name: Docker Publish Prod
# Publish Production images to DockerHub

on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: 3mcloud/lambda-packager
  REGISTRY: ghcr.io
  ORG: 3mcloud

jobs:
  build-python:
    strategy:
      matrix:
        version: [3.8, 3.9, 3.10, 3.11]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "latest,python-latest,python-${{ matrix.version }}"
        context: python/.
        dockerfile: python/${{ matrix.version }}/Dockerfile

    - name: login-to-ghcr
      run: echo "${{ secrets.PACKAGETOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

    - name: push-to-ghcr
      run: |
        IMAGE_ID=${REGISTRY}/${IMAGE_NAME}
        docker image tag ${IMAGE_NAME}:python-${{ matrix.version }} ${IMAGE_ID}:python-${{ matrix.version }}
        docker image tag ${IMAGE_NAME}:python-${{ matrix.version }} ${IMAGE_ID}:latest
        docker image tag ${IMAGE_NAME}:python-${{ matrix.version }} ${IMAGE_ID}:python-latest
        docker image push --all-tags $IMAGE_ID


  build-node14x:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "node-latest,node-14.18"
        context: node/.
        dockerfile: node/14.18/Dockerfile

    - name: login-to-ghcr
      run: echo "${{ secrets.PACKAGETOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

    - name: push-to-ghcr
      run: |
        IMAGE_ID=${REGISTRY}/${IMAGE_NAME}
        docker image tag ${IMAGE_NAME}:node-14.18 ${IMAGE_ID}:node-14.18
        docker image tag ${IMAGE_NAME}:node-14.18 ${IMAGE_ID}:node-14.18
        docker image push --all-tags $IMAGE_ID

  Github-Pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r docs/requirements-docs.pip

      - name: Build Docs
        run: make docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _docs
