name: Docker Image CI

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  build-python36:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Build and test python 3.6
      run: make test VERSION=3.6

  build-python37:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Build and test python 3.7
      run: make test VERSION=3.7

  build-python38:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Build and test python 3.8
      run: make test VERSION=3.8


  build-node12x:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Build and test node 12.x
      run: make test VERSION=12.16 RUNTIME=node
