name: Docker Publish Prod
# Publish Production images to DockerHub

on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: lambda-packager
  REGISTRY: ghcr.io
  ORG: 3mcloud

jobs:
  build-python36-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: build_image
        run: docker build -t $IMAGE_NAME --no-cache -f python/3.6/Dockerfile python/.

      - name: Log into registry
        if: steps.build_image.outcome == 'success'
        run: echo "${{ secrets.PACKAGETOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=${REGISTRY}/${ORG}/${IMAGE_NAME}
          docker image tag ${IMAGE_NAME} ${IMAGE_ID}:python-3.6
          docker image push --all-tags $IMAGE_ID

  build-python36:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "python-3.6"
        context: python/.
        dockerfile: python/3.6/Dockerfile

  build-python37-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: build_image
        run: docker build -t $IMAGE_NAME --no-cache -f python/3.7/Dockerfile python/.

      - name: Log into registry
        if: steps.build_image.outcome == 'success'
        run: echo "${{ secrets.PACKAGETOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=${REGISTRY}/${ORG}/${IMAGE_NAME}
          docker image tag ${IMAGE_NAME} ${IMAGE_ID}:python-3.7
          docker image push --all-tags $IMAGE_ID

  build-python37:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "python-3.7"
        context: python/.
        dockerfile: python/3.7/Dockerfile

  build-python38-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: build_image
        run: docker build -t $IMAGE_NAME --no-cache -f python/3.8/Dockerfile python/.

      - name: Log into registry
        if: steps.build_image.outcome == 'success'
        run: echo "${{ secrets.PACKAGETOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=${REGISTRY}/${ORG}/${IMAGE_NAME}
          docker image tag ${IMAGE_NAME} ${IMAGE_ID}:python-3.8
          docker image push --all-tags $IMAGE_ID

  build-python38:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "python-3.8"
        context: python/.
        dockerfile: python/3.8/Dockerfile

  build-python39-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: build_image
        run: docker build -t $IMAGE_NAME --no-cache -f python/3.9/Dockerfile python/.

      - name: Log into registry
        if: steps.build_image.outcome == 'success'
        run: echo "${{ secrets.PACKAGETOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=${REGISTRY}/${ORG}/${IMAGE_NAME}
          docker image tag ${IMAGE_NAME} ${IMAGE_ID}:python-3.9
          docker image tag ${IMAGE_NAME} ${IMAGE_ID}:python-latest
          docker image tag ${IMAGE_NAME} ${IMAGE_ID}:latest
          docker image push --all-tags $IMAGE_ID

  build-python39:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "latest,python-latest,python-3.9"
        context: python/.
        dockerfile: python/3.9/Dockerfile

  build-node12x-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: build_image
        run: docker build -t $IMAGE_NAME --no-cache -f node/12.22/Dockerfile node/.

      - name: Log into registry
        if: steps.build_image.outcome == 'success'
        run: echo "${{ secrets.PACKAGETOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=${REGISTRY}/${ORG}/${IMAGE_NAME}
          docker image tag ${IMAGE_NAME} ${IMAGE_ID}:node-12.22
          docker image push --all-tags $IMAGE_ID

  build-node12x:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "node-12.22"
        context: node/.
        dockerfile: node/12.22/Dockerfile

  build-node14x-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: build_image
        run: docker build -t $IMAGE_NAME --no-cache -f node/14.18/Dockerfile node/.

      - name: Log into registry
        if: steps.build_image.outcome == 'success'
        run: echo "${{ secrets.PACKAGETOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=${REGISTRY}/${ORG}/${IMAGE_NAME}
          docker image tag ${IMAGE_NAME} ${IMAGE_ID}:node-14.18
          docker image tag ${IMAGE_NAME} ${IMAGE_ID}:node-latest
          docker image push --all-tags $IMAGE_ID

  build-node14x:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: 3mcloud/lambda-packager
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBPASS }}
        tags: "node-latest,node-14.18"
        context: node/.
        dockerfile: node/14.18/Dockerfile
